# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c9b2f3f2f9c07f96e0e636318a02ed9a3dc393faac1e70fb2473e34e4a3ef92cc3cab3931baaea2c282d910494a430c87142246586699e564c3092f38255d4

test:
  secret_key_base: de53306a7633f81c3c6e2f567cc437499624be6e4a04789f5c2b7b590822b1f143788a2a58ec449227879c41448e83916eb1b2d66943debdc1180c8474446f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
